### ISSUE TITLE
Testing Data? 

### ISSUE THREAD

**Issue by zdrever** [zdrever/MiniProject#11]
We are going to need some testing data along the way. When should it be done? Who wants to make it? Could we ask another group for their data?

**Comment by abidrahman** [comment]
- Pick data set from Assignment 2 (Provided by TA's) and add missing columns for a few tables + the agent table.

**Comment by gillianpierce** [comment]
I added some test data (the one prepared for assignment 2 by Benjamin Lavin) added some entries to the agents table and updated the customers table with passwords
