### ISSUE TITLE
Login Screen 

### ISSUE THREAD

**Issue by abidrahman** [zdrever/MiniProject#2]
The first screen should provide options for both customers and agents. There must be also an option to exit the program. Registered customers should be able to login using a valid id and password, denoted with cid and pwd in table customers. Agents should be able to login using a valid id and password, denoted with aid and pwd in table agents. Both customers and agents should be able to logout.

Unregistered customers should be able to sign up by providing a unique id, a name, an address, and a password. Proper messages should be given if the provided id is not unique. All agents are registered by the system admin, and you will assume in your application that they are all registered. After a successful login or signup, customers and agents should be able to perform the subsequent operations (possibly chosen from a menu) as discussed next.

**Comment by gillianpierce** [comment]
Login screen implemented. Customers and agents can log in and new customers can sign up. Once logged in users are presented with appropriate options for actions they can take within the interface
