### ISSUE TITLE
SysFunc Customer 1: Search for products

### ISSUE THREAD

**Issue by abidrahman** [zdrever/MiniProject#3]
The customer should be able to enter one or more keyword and the system should retrieve every product that match at least one of the keywords. A product in a store matches a keyword if the keyword appears in the product name. Order the result based on the number of keyword matches with the product name and the store name in a descending order (with the product that has the largest number of matches listed first). For each matching product, list the product id, name, unit, the number of stores that carry it, the number of stores that have it in stock, the minimum price among the stores that carry it, the minimum price among the stores that have the product in stock, and the number of orders within the past 7 days. If there are more than 5 matching products, only 5 would be shown and the user would be given an option to see more but again 5 at a time. The user should be able to select a product and see more detail about the product including the product id, name, unit, category and a listing of all stores that carry the product with their prices, quantities in stock and the number of orders within the past 7 days. If a product is carried by more than one store, the result should be ordered as follows: (1) the stores that have the product in stock will be listed before those that don't; (2) the stores in each case will be sorted based on the store price (from lowest to highest). The user should be able to select a product from a store and add it to his/her basket. The default quantity should be set to 1, but the user should be able to change the quantity. The basket is deleted after the customer logs out or places an order.

**Comment by gillianpierce** [comment]
Basic search functionality is implemented.  Products matching an arbitrary number of comma separated keywords can be performed. Results are limited to 5. Unable to see more info about products, see additional matching products or add products to the basket

**Comment by zdrever** [comment]
THIS ONES FOOKIN DONE
