### ISSUE TITLE
SysFunc Customer 2: Place an order

### ISSUE THREAD

**Issue by abidrahman** [zdrever/MiniProject#4]
The customer should be able to order the products in his/her basket. The user should be notified if the store quantity for a product is less than the quantity in the basket, which may happen if the quantity is set too high at the time of the order or if the product is ordered by another customer after the customer added it to the basket and before placing an order. In such cases, the user should be given the option to change the quantity or delete the product from the basket. If all products are in stores and have sufficient quantities, an order should be placed for the customer. A unique order number should be generated by your program and the order details should be recorded in the appropriate tables.

**Comment by zdrever** [comment]
DONE
