### ISSUE TITLE
SysFunc Customer 3: List Orders

### ISSUE THREAD

**Issue by abidrahman** [zdrever/MiniProject#5]
The customer should be able to see all his/her orders; the listing should include for each order, the order id, order date, the number of products ordered and the total price; the orders should be listed in a sorted order with more recent orders listed first. If there are more than 5 orders, only 5 would be shown and the user would be given an option to see more but again 5 at a time. The user should be able to select an order and see more detail of the order including delivery information such as tracking number, pick up and drop off times, the address to be delivered, and a listing of the products in the order, which will include for each product the store id, the store name, the product id, the product name, quantity, unit and unit price.

**Comment by gillianpierce** [comment]
All of a customers orders are listed. Not yet limited and customers can't see more info about their orders yet.

**Comment by gillianpierce** [comment]
More info can now be displayed by selecting the line number

**Comment by zdrever** [comment]
Tired of coding. The only thing that still needs to be done is paginating the list of orders.

**Comment by zdrever** [comment]
PAGINATING DONE
